name: Create Tag on Push to Dev

on:
  push:
    branches:
      - dev # Trigger the action when there is a push to the 'dev' branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit message
        id: get_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')  # Get the latest commit message
          echo "commit_message=${COMMIT_MESSAGE}" >> $GITHUB_ENV  # Set the commit message as an environment variable

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          TAG_NAME="${{ env.commit_message }}"  # Use the commit message as the tag name
          TAG_NAME="${TAG_NAME//[^a-zA-Z0-9._-]/-}"  # Replace invalid characters with dashes
          git tag "$TAG_NAME"  # Create a new tag
          git push origin "$TAG_NAME"  # Push the new tag to the repository
